### ISSUE TITLE
MasterNode_Setup_Cold_Hot_Windows

### ISSUE THREAD

**Issue by ghost** [shekeltechnologies/Documentation#1]
The person who contributes with a Windows hot wallet equivalent of this:

https://github.com/shekeltechnologies/Documentation/blob/master/guides/MasterNode_Setup_Cold_Hot_Linux.md

Gets at least 1000 JEW coins from the foundation.

**If you would like to support this community initiative, please state how many coins you are willing to throw in ;)**

**Comment by binbashblog** [comment]
It's coming :)

**Comment by ghost** [comment]
Man, you are up for a challenge!!! Much appreciated!

**Comment by binbashblog** [comment]
DONE

Masternode_Setup_Hot_Windows.md

**Comment by binbashblog** [comment]
I'll let you review and close when you're happy lol

**Comment by ghost** [comment]
Looks very good, great contribution.
Just changed the link to it from the main page so it's similar with the Linux one.
